### ISSUE TITLE
SMSMessageHandler strategy is not persistent

### ISSUE THREAD

**Issue by CremaLuca** [Cogno-IDU/smslibrary#18]
@RicDeZen on pull #17 got me thinking that if we were to send a message with a custom strategy, and the receiver app is closed, the strategy used would be the default one, because the strategy is only changed during runtime from the app module, and when `SMSMessageHandler` is closed the reference is lost. We need to find a way to have it persistent, that once it's set it stays the same.

_I just wonder if we already have something that saves **preferences** like that in memory..._

**Comment by Cogno-IDU** [comment]
He also says another interesting thing. What if 2 apps where to use the same smslibrary? if one set a strategy than wouldn't the other also see the same strategy updated? I actually don't know, but I think it might happen since it's a singleton

**Comment by CremaLuca** [comment]
What do you mean 2 apps? If you have two apps that use the same library you would have two instances for two singletons, they're not related because they're from two different processes

**Comment by RicDeZen** [comment]
I'm not really talking about two apps (if I said so I mispelled) more like two modules of the same app, like the library itself, that reads the messages and the network that needs to send actions to other Peers (is the strategy meant for stuff like this too? If not, I misinterpreted)

**Comment by CremaLuca** [comment]
This one issue is about having the strategy persistent within **one** library of **one** app, it's more basic than the discussion going on in the pull request

**Comment by Cogno-IDU** [comment]
Oh right, they would be separate...
This would be a fun discussion to do all together btw. If no one finds a way I'd like to discuss it IRL 😄

**Comment by CremaLuca** [comment]
What if, like it's been done with background handling, we were to save the strategy class name in memory and instantiate it when needed?

**Comment by Cogno-IDU** [comment]
Convert from a string to a class? what?

**Comment by Cogno-IDU** [comment]
unless it becomes a switch (if more strategy are present). Code smell

**Comment by CremaLuca** [comment]
Agreed with @RicDeZen to fix this in pull request #17
