### ISSUE TITLE
 too little testability

### ISSUE THREAD

**Issue by MattiaFanan-uni** [Cogno-IDU/smslibrary#24]
in my opinion it's better to pass SmsManager to SMSCore and SMSCore to SMSHandler from the outside

**Comment by CremaLuca** [comment]
I was thinking about this too yesterday:
`SMSCore` is a Singleton, there can't be two of them it wouldn't make any sense. We could have a method like `setup(android.SmsManager)` (to be consistent with singleton setup methods) or `setSmsManager(android.SmsManager)`, it's not strictly required to call these methods but we give the possibility to change the default SmsManager class.
In `SMSHanlder` we could have an override of `setup(Context)` like `setup(Context, SMSCore)` which, again, would be optional.

**Comment by MattiaFanan-uni** [comment]
it's the problem of Singleton
if two use the same singleton and change internal config none of the two have a singleton in consistent state

**Comment by CremaLuca** [comment]
It's not a "problem", it's a wanted characteristic of the singleton, to be in the same state for everybody

**Comment by MattiaFanan-uni** [comment]
and this is the reason i think the professor suggest us to change to object pool

**Comment by Cogno-IDU** [comment]
The object pool suggestion only refers to my code in the replicated network, not for smslibrary

**Comment by Cogno-IDU** [comment]
Also SMSCore is static (so you can't test it), but hey, guess what, we have an entire pull-request where I specifically created Mock tests to tst SMSHandler ( #15 ). Check that out first!

**Comment by MattiaFanan-uni** [comment]
for SMSCore i agree with you
but change the context inside the singleton bah

**Comment by MattiaFanan-uni** [comment]
> It's not a "problem", it's a wanted characteristic of the singleton, to be in the same state for everybody

it's in the wrong state for n-1 objects

**Comment by MattiaFanan-uni** [comment]
pretend that I didn't say anything
