### ISSUE TITLE
Avoid unused imports such as 'androidx.annotation.NonNull'

### ISSUE THREAD

**Issue by CremaLuca** [Cogno-IDU/smslibrary#28]
#### Occurred on:
+ **Commit**:  b82dce17e90c898eeb7827be3969ba7f36c042dc
+ **File**:    [smslibrary/src/main/java/com/eis/communication/Peer.java](https://github.com/Cogno-IDU/smslibrary/blob/b82dce17e90c898eeb7827be3969ba7f36c042dc/smslibrary/src/main/java/com/eis/communication/Peer.java)
+ **LineNum**: [3](https://github.com/Cogno-IDU/smslibrary/blob/b82dce17e90c898eeb7827be3969ba7f36c042dc/smslibrary/src/main/java/com/eis/communication/Peer.java#L3)
+ **Code**:    `import androidx.annotation.NonNull;`

    
#### Currently on:
+ **Commit**:  6b48074ebecfdb01ee083651adb8bf66b75b4674
+ **File**:    [smslibrary/src/main/java/com/eis/communication/Peer.java](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/main/java/com/eis/communication/Peer.java)
+ **LineNum**: [3](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/main/java/com/eis/communication/Peer.java#L3)

**Comment by Cogno-IDU** [comment]
Solved in #34
