### ISSUE TITLE
Switch statements should have a default label

### ISSUE THREAD

**Issue by CremaLuca** [Cogno-IDU/smslibrary#29]
#### Currently on:
+ **Commit**:  6b48074ebecfdb01ee083651adb8bf66b75b4674
+ **File**:    [smslibrary/src/main/java/com/eis/smslibrary/SMSDeliveredBroadcastReceiver.java](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/main/java/com/eis/smslibrary/SMSDeliveredBroadcastReceiver.java)
+ **LineNum**: [44](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/main/java/com/eis/smslibrary/SMSDeliveredBroadcastReceiver.java#L44)

**Comment by Cogno-IDU** [comment]
Solved in #34
