### ISSUE TITLE
Avoid using equals() to compare against null

### ISSUE THREAD

**Issue by CremaLuca** [Cogno-IDU/smslibrary#32]
#### Occurred on:
+ **Commit**:  7ead30b4b87b425b5426486431f1507341a4beb3
+ **File**:    [smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java](https://github.com/Cogno-IDU/smslibrary/blob/7ead30b4b87b425b5426486431f1507341a4beb3/smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java)
+ **LineNum**: [126](https://github.com/Cogno-IDU/smslibrary/blob/7ead30b4b87b425b5426486431f1507341a4beb3/smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java#L126)
+ **Code**:    `Assert.assertFalse(defaultPeer1.equals(null));`

    
#### Currently on:
+ **Commit**:  6b48074ebecfdb01ee083651adb8bf66b75b4674
+ **File**:    [smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java)
+ **LineNum**: [126](https://github.com/Cogno-IDU/smslibrary/blob/6b48074ebecfdb01ee083651adb8bf66b75b4674/smslibrary/src/test/java/com/eis/smslibrary/SMSPeerTest.java#L126)

**Comment by MattiaFanan-uni** [comment]
![image](https://user-images.githubusercontent.com/56410189/70849271-969ef800-1e7c-11ea-80e3-e7ebc867a1d3.png)
but our intentions are to test equals override

**Comment by Cogno-IDU** [comment]
Solved in #34
