### ISSUE TITLE
Tagging suggestion

### ISSUE THREAD

**Issue by MatteoCarnelos** [Cogno-IDU/smslibrary#33]
As GitHub suggests:

> It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0 or v2.3.4.

Wouldn't be better to remove the dash in the actual tag names? Thus making them become `v1.0` and `v2.0`.

**Comment by CremaLuca** [comment]
They're actually `v-1.0`. Is it *that* different from `v1.0`?

**Comment by CremaLuca** [comment]
Sure, might be a good standardization.

**Comment by CremaLuca** [comment]
Since `v2.1` we adopted this. Marking it as closed.
https://github.com/Cogno-IDU/smslibrary/releases/tag/v2.1
